spring.application.name=bucket
spring.datasource.url = jdbc:mysql://localhost:3306/users
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
jwt.secret = ${SECRET_KEY}
spring.jpa.hibernate.ddl-auto = update

 